import streamlit as st
from utils.state import is_authenticated, init_session_state
from components.auth_forms import render_auth_gate

st.set_page_config(
    page_title="Spotigram",
    page_icon="🎵",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Load CSS if it exists
try:
    with open("assets/style.css") as f:
        st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)
except FileNotFoundError:
    pass

init_session_state()

if not is_authenticated():
    render_auth_gate()
else:
    # If authenticated, the user will see the sidebar generated by Streamlit's multipage app 
    # but since this is the entry point, we can just redirect them or show a welcome screen
    st.switch_page("pages/01_Home.py")
