apiVersion: v1
kind: Secret
metadata:
  name: spotigram-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://user:password@postgres-service:5432/spotigram"
  # Add other sensitive secrets here
